import { MongoClient } from "mongodb"

const MONGODB_URI = "mongodb+srv://selshenawy69_db_user:DuTikBeEzvyxhryQ@mean-t4.v8igppx.mongodb.net/electronics?retryWrites=true&w=majority";

const Products = [
  {
    name: "iPhone 15 Pro",
    description: "Latest iPhone with A17 Pro chip, titanium design, and advanced camera system",
    price: 999.99,
    category: "smartphones",
    brand: "Apple",
    images: ["/images/iphone-15-pro-1.jpg", "/images/iphone-15-pro-2.jpg"],
    specifications: {
      display: "6.1-inch Super Retina XDR",
      processor: "A17 Pro chip",
      storage: "128GB",
      camera: "48MP Main, 12MP Ultra Wide, 12MP Telephoto",
      battery: "Up to 23 hours video playback",
    },
    stock: 50,
    sku: "IPHONE-15-PRO-128",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "MacBook Pro 14-inch",
    description: "Powerful laptop with M3 chip, perfect for professionals and creators",
    price: 1999.99,
    category: "laptops",
    brand: "Apple",
    images: ["/images/macbook-pro-14-1.jpg", "/images/macbook-pro-14-2.jpg"],
    specifications: {
      processor: "Apple M3 chip",
      memory: "16GB unified memory",
      storage: "512GB SSD",
      display: "14.2-inch Liquid Retina XDR",
      battery: "Up to 18 hours",
    },
    stock: 25,
    sku: "MBP-14-M3-512",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    description: "Premium Android smartphone with S Pen and advanced AI features",
    price: 1199.99,
    category: "smartphones",
    brand: "Samsung",
    images: ["/images/galaxy-s24-ultra-1.jpg", "/images/galaxy-s24-ultra-2.jpg"],
    specifications: {
      display: "6.8-inch Dynamic AMOLED 2X",
      processor: "Snapdragon 8 Gen 3",
      storage: "256GB",
      camera: "200MP Main, 50MP Periscope Telephoto, 10MP Telephoto, 12MP Ultra Wide",
      battery: "5000mAh",
    },
    stock: 40,
    sku: "GALAXY-S24-ULTRA-256",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Dell XPS 13",
    description: "Ultra-portable laptop with stunning InfinityEdge display",
    price: 1299.99,
    category: "laptops",
    brand: "Dell",
    images: ["/images/dell-xps-13-1.jpg", "/images/dell-xps-13-2.jpg"],
    specifications: {
      processor: "Intel Core i7-1360P",
      memory: "16GB LPDDR5",
      storage: "512GB SSD",
      display: "13.4-inch FHD+ InfinityEdge",
      battery: "Up to 12 hours",
    },
    stock: 30,
    sku: "DELL-XPS-13-I7-512",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Sony WH-1000XM5",
    description: "Industry-leading noise canceling wireless headphones",
    price: 399.99,
    category: "audio",
    brand: "Sony",
    images: ["/images/sony-wh1000xm5-1.jpg", "/images/sony-wh1000xm5-2.jpg"],
    specifications: {
      type: "Over-ear wireless headphones",
      noiseCanceling: "Industry-leading noise canceling",
      battery: "Up to 30 hours",
      connectivity: "Bluetooth 5.2, NFC",
      features: "Touch controls, voice assistant support",
    },
    stock: 75,
    sku: "SONY-WH1000XM5-BLACK",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "iPad Pro 12.9-inch",
    description: "Most advanced iPad with M2 chip and Liquid Retina XDR display",
    price: 1099.99,
    category: "tablets",
    brand: "Apple",
    images: ["/images/ipad-pro-12-1.jpg", "/images/ipad-pro-12-2.jpg"],
    specifications: {
      display: "12.9-inch Liquid Retina XDR",
      processor: "Apple M2 chip",
      storage: "128GB",
      camera: "12MP Wide, 10MP Ultra Wide",
      connectivity: "Wi-Fi 6E, 5G (cellular models)",
    },
    stock: 35,
    sku: "IPAD-PRO-12-M2-128",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Google Pixel 8 Pro",
    description: "AI-powered smartphone with advanced computational photography",
    price: 899.99,
    category: "smartphones",
    brand: "Google",
    images: ["/images/pixel-8-pro-1.jpg", "/images/pixel-8-pro-2.jpg"],
    specifications: {
      display: "6.7-inch LTPO OLED",
      processor: "Google Tensor G3",
      storage: "128GB",
      camera: "50MP Main, 48MP Ultra Wide, 48MP Telephoto",
      battery: "5050mAh",
    },
    stock: 45,
    sku: "PIXEL-8-PRO-128",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "OnePlus 12",
    description: "Flagship smartphone with Snapdragon 8 Gen 3 and fast charging",
    price: 799.99,
    category: "smartphones",
    brand: "OnePlus",
    images: ["/images/oneplus-12-1.jpg", "/images/oneplus-12-2.jpg"],
    specifications: {
      display: "6.82-inch LTPO AMOLED",
      processor: "Snapdragon 8 Gen 3",
      storage: "256GB",
      camera: "50MP Main, 64MP Periscope, 48MP Ultra Wide",
      battery: "5400mAh with 100W charging",
    },
    stock: 35,
    sku: "ONEPLUS-12-256",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "iPhone 14",
    description: "Reliable iPhone with A15 Bionic chip and improved cameras",
    price: 699.99,
    category: "smartphones",
    brand: "Apple",
    images: ["/images/iphone-14-1.jpg", "/images/iphone-14-2.jpg"],
    specifications: {
      display: "6.1-inch Super Retina XDR",
      processor: "A15 Bionic chip",
      storage: "128GB",
      camera: "12MP Main, 12MP Ultra Wide",
      battery: "Up to 20 hours video playback",
    },
    stock: 60,
    sku: "IPHONE-14-128",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Samsung Galaxy A54",
    description: "Mid-range smartphone with great camera and long battery life",
    price: 449.99,
    category: "smartphones",
    brand: "Samsung",
    images: ["/images/galaxy-a54-1.jpg", "/images/galaxy-a54-2.jpg"],
    specifications: {
      display: "6.4-inch Super AMOLED",
      processor: "Exynos 1380",
      storage: "128GB",
      camera: "50MP Main, 12MP Ultra Wide, 5MP Macro",
      battery: "5000mAh",
    },
    stock: 80,
    sku: "GALAXY-A54-128",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "MacBook Air M2",
    description: "Thin and light laptop with M2 chip and all-day battery life",
    price: 1199.99,
    category: "laptops",
    brand: "Apple",
    images: ["/images/macbook-air-m2-1.jpg", "/images/macbook-air-m2-2.jpg"],
    specifications: {
      processor: "Apple M2 chip",
      memory: "8GB unified memory",
      storage: "256GB SSD",
      display: "13.6-inch Liquid Retina",
      battery: "Up to 18 hours",
    },
    stock: 40,
    sku: "MBA-M2-256",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "HP Spectre x360",
    description: "Premium 2-in-1 laptop with OLED display and stylus support",
    price: 1399.99,
    category: "laptops",
    brand: "HP",
    images: ["/images/hp-spectre-x360-1.jpg", "/images/hp-spectre-x360-2.jpg"],
    specifications: {
      processor: "Intel Core i7-1355U",
      memory: "16GB LPDDR5",
      storage: "512GB SSD",
      display: "13.5-inch OLED touchscreen",
      battery: "Up to 10 hours",
    },
    stock: 25,
    sku: "HP-SPECTRE-X360-512",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Lenovo ThinkPad X1 Carbon",
    description: "Business laptop with robust build and excellent keyboard",
    price: 1599.99,
    category: "laptops",
    brand: "Lenovo",
    images: ["/images/thinkpad-x1-carbon-1.jpg", "/images/thinkpad-x1-carbon-2.jpg"],
    specifications: {
      processor: "Intel Core i7-1365U",
      memory: "16GB LPDDR5",
      storage: "512GB SSD",
      display: "14-inch WUXGA IPS",
      battery: "Up to 15 hours",
    },
    stock: 30,
    sku: "THINKPAD-X1-CARBON-512",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "ASUS ROG Zephyrus G14",
    description: "Gaming laptop with AMD Ryzen and RTX graphics",
    price: 1799.99,
    category: "laptops",
    brand: "ASUS",
    images: ["/images/rog-zephyrus-g14-1.jpg", "/images/rog-zephyrus-g14-2.jpg"],
    specifications: {
      processor: "AMD Ryzen 9 7940HS",
      memory: "16GB DDR5",
      storage: "1TB SSD",
      display: "14-inch QHD 165Hz",
      graphics: "NVIDIA RTX 4060",
    },
    stock: 20,
    sku: "ROG-ZEPHYRUS-G14-1TB",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Microsoft Surface Laptop 5",
    description: "Elegant laptop with premium design and Windows 11",
    price: 1299.99,
    category: "laptops",
    brand: "Microsoft",
    images: ["/images/surface-laptop-5-1.jpg", "/images/surface-laptop-5-2.jpg"],
    specifications: {
      processor: "Intel Core i7-1255U",
      memory: "16GB LPDDR5x",
      storage: "512GB SSD",
      display: "13.5-inch PixelSense touchscreen",
      battery: "Up to 17 hours",
    },
    stock: 35,
    sku: "SURFACE-LAPTOP-5-512",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "iPad Air",
    description: "Versatile iPad with M1 chip and Apple Pencil support",
    price: 599.99,
    category: "tablets",
    brand: "Apple",
    images: ["/images/ipad-air-1.jpg", "/images/ipad-air-2.jpg"],
    specifications: {
      display: "10.9-inch Liquid Retina",
      processor: "Apple M1 chip",
      storage: "64GB",
      camera: "12MP Wide",
      connectivity: "Wi-Fi 6, USB-C",
    },
    stock: 50,
    sku: "IPAD-AIR-M1-64",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Samsung Galaxy Tab S9",
    description: "Premium Android tablet with S Pen included",
    price: 799.99,
    category: "tablets",
    brand: "Samsung",
    images: ["/images/galaxy-tab-s9-1.jpg", "/images/galaxy-tab-s9-2.jpg"],
    specifications: {
      display: "11-inch Dynamic AMOLED 2X",
      processor: "Snapdragon 8 Gen 2",
      storage: "128GB",
      camera: "13MP Main, 6MP Ultra Wide",
      features: "S Pen included, IP68 rating",
    },
    stock: 40,
    sku: "GALAXY-TAB-S9-128",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Microsoft Surface Pro 9",
    description: "2-in-1 tablet with laptop performance and detachable keyboard",
    price: 999.99,
    category: "tablets",
    brand: "Microsoft",
    images: ["/images/surface-pro-9-1.jpg", "/images/surface-pro-9-2.jpg"],
    specifications: {
      display: "13-inch PixelSense Flow",
      processor: "Intel Core i5-1235U",
      memory: "8GB LPDDR5",
      storage: "256GB SSD",
      connectivity: "Wi-Fi 6E, Bluetooth 5.1",
    },
    stock: 30,
    sku: "SURFACE-PRO-9-256",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Amazon Fire HD 10",
    description: "Affordable tablet for entertainment and reading",
    price: 149.99,
    category: "tablets",
    brand: "Amazon",
    images: ["/images/fire-hd-10-1.jpg", "/images/fire-hd-10-2.jpg"],
    specifications: {
      display: "10.1-inch Full HD",
      processor: "Octa-core 2.0 GHz",
      storage: "32GB",
      battery: "Up to 12 hours",
      features: "Alexa hands-free, expandable storage",
    },
    stock: 100,
    sku: "FIRE-HD-10-32",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "AirPods Pro 2nd Gen",
    description: "Premium wireless earbuds with active noise cancellation",
    price: 249.99,
    category: "audio",
    brand: "Apple",
    images: ["/images/airpods-pro-2-1.jpg", "/images/airpods-pro-2-2.jpg"],
    specifications: {
      type: "In-ear wireless earbuds",
      noiseCanceling: "Active Noise Cancellation",
      battery: "Up to 6 hours (30 hours with case)",
      connectivity: "Bluetooth 5.3",
      features: "Spatial Audio, Touch controls",
    },
    stock: 120,
    sku: "AIRPODS-PRO-2",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bose QuietComfort 45",
    description: "Comfortable noise-canceling headphones for all-day wear",
    price: 329.99,
    category: "audio",
    brand: "Bose",
    images: ["/images/bose-qc45-1.jpg", "/images/bose-qc45-2.jpg"],
    specifications: {
      type: "Over-ear wireless headphones",
      noiseCanceling: "Quiet Mode and Aware Mode",
      battery: "Up to 24 hours",
      connectivity: "Bluetooth 5.1",
      features: "Voice assistant support, quick charge",
    },
    stock: 60,
    sku: "BOSE-QC45-BLACK",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "JBL Flip 6",
    description: "Portable Bluetooth speaker with powerful sound",
    price: 129.99,
    category: "audio",
    brand: "JBL",
    images: ["/images/jbl-flip-6-1.jpg", "/images/jbl-flip-6-2.jpg"],
    specifications: {
      type: "Portable Bluetooth speaker",
      battery: "Up to 12 hours",
      connectivity: "Bluetooth 5.1",
      features: "IP67 waterproof, PartyBoost",
      power: "20W RMS",
    },
    stock: 80,
    sku: "JBL-FLIP-6-BLACK",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Sennheiser HD 660S2",
    description: "Open-back audiophile headphones for critical listening",
    price: 599.99,
    category: "audio",
    brand: "Sennheiser",
    images: ["/images/sennheiser-hd660s2-1.jpg", "/images/sennheiser-hd660s2-2.jpg"],
    specifications: {
      type: "Open-back wired headphones",
      impedance: "150 ohms",
      frequency: "8 Hz - 41,500 Hz",
      connector: "6.3mm jack (3.5mm adapter included)",
      features: "Replaceable cable, premium build",
    },
    stock: 25,
    sku: "SENNHEISER-HD660S2",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "PlayStation 5",
    description: "Next-gen gaming console with ultra-high speed SSD",
    price: 499.99,
    category: "gaming",
    brand: "Sony",
    images: ["/images/ps5-1.jpg", "/images/ps5-2.jpg"],
    specifications: {
      processor: "AMD Zen 2 8-core CPU",
      graphics: "AMD RDNA 2 GPU",
      storage: "825GB SSD",
      memory: "16GB GDDR6",
      features: "4K gaming, Ray tracing, 3D Audio",
    },
    stock: 15,
    sku: "PS5-CONSOLE",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Xbox Series X",
    description: "Most powerful Xbox with 4K gaming and Quick Resume",
    price: 499.99,
    category: "gaming",
    brand: "Microsoft",
    images: ["/images/xbox-series-x-1.jpg", "/images/xbox-series-x-2.jpg"],
    specifications: {
      processor: "AMD Zen 2 8-core CPU",
      graphics: "AMD RDNA 2 GPU",
      storage: "1TB SSD",
      memory: "16GB GDDR6",
      features: "4K gaming, Ray tracing, Quick Resume",
    },
    stock: 20,
    sku: "XBOX-SERIES-X",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Nintendo Switch OLED",
    description: "Portable gaming console with vibrant OLED screen",
    price: 349.99,
    category: "gaming",
    brand: "Nintendo",
    images: ["/images/switch-oled-1.jpg", "/images/switch-oled-2.jpg"],
    specifications: {
      display: "7-inch OLED touchscreen",
      storage: "64GB internal",
      battery: "4.5 - 9 hours",
      connectivity: "Wi-Fi, Bluetooth 4.1",
      features: "Handheld and docked modes",
    },
    stock: 45,
    sku: "SWITCH-OLED-WHITE",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Steam Deck",
    description: "Handheld PC gaming device with SteamOS",
    price: 399.99,
    category: "gaming",
    brand: "Valve",
    images: ["/images/steam-deck-1.jpg", "/images/steam-deck-2.jpg"],
    specifications: {
      processor: "AMD APU (Zen 2 + RDNA 2)",
      display: "7-inch LCD touchscreen",
      storage: "64GB eMMC",
      memory: "16GB LPDDR5",
      features: "Full PC gaming library, Linux-based OS",
    },
    stock: 30,
    sku: "STEAM-DECK-64GB",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Amazon Echo Dot 5th Gen",
    description: "Smart speaker with Alexa voice assistant",
    price: 49.99,
    category: "smart-home",
    brand: "Amazon",
    images: ["/images/echo-dot-5-1.jpg", "/images/echo-dot-5-2.jpg"],
    specifications: {
      type: "Smart speaker",
      assistant: "Alexa built-in",
      connectivity: "Wi-Fi, Bluetooth",
      features: "Voice control, smart home hub",
      audio: "Improved bass and clearer vocals",
    },
    stock: 150,
    sku: "ECHO-DOT-5-CHARCOAL",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Google Nest Hub 2nd Gen",
    description: "Smart display with Google Assistant and sleep tracking",
    price: 99.99,
    category: "smart-home",
    brand: "Google",
    images: ["/images/nest-hub-2-1.jpg", "/images/nest-hub-2-2.jpg"],
    specifications: {
      display: "7-inch touchscreen",
      assistant: "Google Assistant built-in",
      features: "Sleep sensing, smart home control",
      connectivity: "Wi-Fi, Bluetooth",
      camera: "No camera for privacy",
    },
    stock: 75,
    sku: "NEST-HUB-2-CHALK",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Apple Watch Series 9",
    description: "Advanced smartwatch with health monitoring and fitness tracking",
    price: 399.99,
    category: "wearables",
    brand: "Apple",
    images: ["/images/apple-watch-s9-1.jpg", "/images/apple-watch-s9-2.jpg"],
    specifications: {
      display: "45mm Retina LTPO OLED",
      processor: "S9 SiP",
      features: "ECG, Blood Oxygen, Always-On display",
      battery: "Up to 18 hours",
      connectivity: "GPS, Cellular (optional)",
    },
    stock: 60,
    sku: "APPLE-WATCH-S9-45MM",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Samsung Galaxy Watch 6",
    description: "Android smartwatch with comprehensive health tracking",
    price: 329.99,
    category: "wearables",
    brand: "Samsung",
    images: ["/images/galaxy-watch-6-1.jpg", "/images/galaxy-watch-6-2.jpg"],
    specifications: {
      display: "44mm Super AMOLED",
      processor: "Exynos W930",
      features: "Body composition, sleep tracking, GPS",
      battery: "Up to 40 hours",
      os: "Wear OS powered by Samsung",
    },
    stock: 45,
    sku: "GALAXY-WATCH-6-44MM",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Canon EOS R6 Mark II",
    description: "Full-frame mirrorless camera for professionals and enthusiasts",
    price: 2499.99,
    category: "cameras",
    brand: "Canon",
    images: ["/images/canon-r6-mark2-1.jpg", "/images/canon-r6-mark2-2.jpg"],
    specifications: {
      sensor: "24.2MP Full-Frame CMOS",
      processor: "DIGIC X",
      video: "4K 60p, Full HD 180p",
      autofocus: "Dual Pixel CMOS AF II",
      stabilization: "In-body 8-stop IS",
    },
    stock: 15,
    sku: "CANON-R6-MARK2-BODY",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Sony A7 IV",
    description: "Versatile full-frame camera with excellent video capabilities",
    price: 2199.99,
    category: "cameras",
    brand: "Sony",
    images: ["/images/sony-a7-iv-1.jpg", "/images/sony-a7-iv-2.jpg"],
    specifications: {
      sensor: "33MP Full-Frame Exmor R",
      processor: "BIONZ XR",
      video: "4K 60p, S-Log3",
      autofocus: "759-point phase detection",
      stabilization: "5-axis in-body",
    },
    stock: 20,
    sku: "SONY-A7-IV-BODY",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "DJI Mini 4 Pro",
    description: "Compact drone with 4K HDR video and intelligent features",
    price: 759.99,
    category: "cameras",
    brand: "DJI",
    images: ["/images/dji-mini-4-pro-1.jpg", "/images/dji-mini-4-pro-2.jpg"],
    specifications: {
      camera: "1/1.3-inch CMOS, 48MP",
      video: "4K/60fps HDR",
      flight: "Up to 34 minutes",
      range: "20km (FCC)",
      features: "Obstacle sensing, ActiveTrack 360°",
    },
    stock: 35,
    sku: "DJI-MINI-4-PRO",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Logitech MX Master 3S",
    description: "Advanced wireless mouse for productivity and precision",
    price: 99.99,
    category: "accessories",
    brand: "Logitech",
    images: ["/images/mx-master-3s-1.jpg", "/images/mx-master-3s-2.jpg"],
    specifications: {
      type: "Wireless mouse",
      sensor: "Darkfield high precision",
      battery: "Up to 70 days",
      connectivity: "Bluetooth, USB-C receiver",
      features: "Multi-device, customizable buttons",
    },
    stock: 100,
    sku: "LOGITECH-MX-MASTER-3S",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Keychron K8 Pro",
    description: "Wireless mechanical keyboard with hot-swappable switches",
    price: 199.99,
    category: "accessories",
    brand: "Keychron",
    images: ["/images/keychron-k8-pro-1.jpg", "/images/keychron-k8-pro-2.jpg"],
    specifications: {
      layout: "87-key tenkeyless",
      switches: "Gateron Pro Red (hot-swappable)",
      connectivity: "Wireless 2.4GHz, Bluetooth, USB-C",
      battery: "Up to 240 hours",
      features: "RGB backlight, aluminum frame",
    },
    stock: 50,
    sku: "KEYCHRON-K8-PRO-RED",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "LG UltraWide 34WP65C",
    description: "34-inch curved ultrawide monitor for productivity and gaming",
    price: 399.99,
    category: "monitors",
    brand: "LG",
    images: ["/images/lg-ultrawide-34wp65c-1.jpg", "/images/lg-ultrawide-34wp65c-2.jpg"],
    specifications: {
      size: "34-inch curved",
      resolution: "3440 x 1440 (UWQHD)",
      panel: "VA with HDR10",
      refresh: "160Hz",
      connectivity: "USB-C, HDMI, DisplayPort",
    },
    stock: 25,
    sku: "LG-34WP65C-B",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Dell S2722DC",
    description: "27-inch 4K USB-C monitor with built-in KVM switch",
    price: 449.99,
    category: "monitors",
    brand: "Dell",
    images: ["/images/dell-s2722dc-1.jpg", "/images/dell-s2722dc-2.jpg"],
    specifications: {
      size: "27-inch",
      resolution: "3840 x 2160 (4K UHD)",
      panel: "IPS with 99% sRGB",
      connectivity: "USB-C 65W, HDMI, DisplayPort",
      features: "Built-in KVM, height adjustable",
    },
    stock: 30,
    sku: "DELL-S2722DC",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Samsung T7 Portable SSD",
    description: "Fast and compact external SSD for data storage and transfer",
    price: 129.99,
    category: "storage",
    brand: "Samsung",
    images: ["/images/samsung-t7-1.jpg", "/images/samsung-t7-2.jpg"],
    specifications: {
      capacity: "1TB",
      interface: "USB 3.2 Gen 2",
      speed: "Up to 1,050 MB/s",
      security: "Password protection, AES 256-bit encryption",
      compatibility: "Windows, Mac, Android",
    },
    stock: 80,
    sku: "SAMSUNG-T7-1TB-BLUE",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "ASUS AX6000 WiFi 6 Router",
    description: "High-performance router with WiFi 6 and advanced security",
    price: 299.99,
    category: "networking",
    brand: "ASUS",
    images: ["/images/asus-ax6000-1.jpg", "/images/asus-ax6000-2.jpg"],
    specifications: {
      standard: "WiFi 6 (802.11ax)",
      speed: "Up to 6000 Mbps",
      coverage: "Up to 5000 sq ft",
      ports: "1x 2.5G WAN, 8x Gigabit LAN",
      features: "AiMesh support, AiProtection Pro",
    },
    stock: 40,
    sku: "ASUS-AX6000-BLACK",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Anker PowerCore 26800",
    description: "High-capacity portable charger for multiple devices",
    price: 79.99,
    category: "accessories",
    brand: "Anker",
    images: ["/images/anker-powercore-26800-1.jpg", "/images/anker-powercore-26800-2.jpg"],
    specifications: {
      capacity: "26800mAh",
      output: "3x USB-A ports",
      charging: "PowerIQ and VoltageBoost",
      recharge: "6-7 hours with dual input",
      compatibility: "iPhone, Samsung, tablets",
    },
    stock: 90,
    sku: "ANKER-POWERCORE-26800",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Belkin 3-in-1 Wireless Charger",
    description: "Wireless charging station for iPhone, Apple Watch, and AirPods",
    price: 149.99,
    category: "accessories",
    brand: "Belkin",
    images: ["/images/belkin-3in1-charger-1.jpg", "/images/belkin-3in1-charger-2.jpg"],
    specifications: {
      compatibility: "iPhone 12-15, Apple Watch, AirPods",
      charging: "15W wireless charging",
      design: "Foldable travel-friendly",
      certification: "MFi certified",
      features: "LED indicators, foreign object detection",
    },
    stock: 60,
    sku: "BELKIN-3IN1-WIRELESS-WHITE",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Meta Quest 3",
    description: "Mixed reality headset with improved graphics and comfort",
    price: 499.99,
    category: "vr",
    brand: "Meta",
    images: ["/images/meta-quest-3-1.jpg", "/images/meta-quest-3-2.jpg"],
    specifications: {
      display: "2064 x 2208 per eye",
      processor: "Snapdragon XR2 Gen 2",
      storage: "128GB",
      tracking: "Inside-out tracking",
      features: "Mixed reality, hand tracking",
    },
    stock: 25,
    sku: "META-QUEST-3-128GB",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "PICO 4 Enterprise",
    description: "Business-focused VR headset with advanced tracking",
    price: 899.99,
    category: "vr",
    brand: "ByteDance",
    images: ["/images/pico-4-enterprise-1.jpg", "/images/pico-4-enterprise-2.jpg"],
    specifications: {
      display: "2160 x 2160 per eye",
      processor: "Snapdragon XR2+ Gen 1",
      storage: "256GB",
      tracking: "6DOF inside-out tracking",
      features: "Enterprise management, eye tracking",
    },
    stock: 15,
    sku: "PICO-4-ENTERPRISE-256GB",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Razer DeathAdder V3 Pro",
    description: "Wireless gaming mouse with Focus Pro 30K sensor",
    price: 149.99,
    category: "accessories",
    brand: "Razer",
    images: ["/images/razer-deathadder-v3-pro-1.jpg", "/images/razer-deathadder-v3-pro-2.jpg"],
    specifications: {
      sensor: "Focus Pro 30K",
      dpi: "Up to 30,000 DPI",
      battery: "Up to 90 hours",
      connectivity: "HyperSpeed Wireless, Bluetooth, USB-C",
      features: "13 programmable buttons, Chroma RGB",
    },
    stock: 75,
    sku: "RAZER-DEATHADDER-V3-PRO",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Corsair K100 RGB",
    description: "Premium mechanical gaming keyboard with OLED display",
    price: 229.99,
    category: "accessories",
    brand: "Corsair",
    images: ["/images/corsair-k100-rgb-1.jpg", "/images/corsair-k100-rgb-2.jpg"],
    specifications: {
      switches: "Cherry MX Speed Silver",
      layout: "Full-size with numpad",
      features: "OLED display, iCUE RGB, media controls",
      connectivity: "USB-C detachable cable",
      polling: "8000Hz polling rate",
    },
    stock: 40,
    sku: "CORSAIR-K100-RGB-SILVER",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "SteelSeries Arctis Nova Pro",
    description: "Premium gaming headset with active noise cancellation",
    price: 349.99,
    category: "audio",
    brand: "SteelSeries",
    images: ["/images/steelseries-arctis-nova-pro-1.jpg", "/images/steelseries-arctis-nova-pro-2.jpg"],
    specifications: {
      drivers: "40mm neodymium drivers",
      frequency: "10Hz - 40,000Hz",
      features: "Active noise cancellation, GameDAC Gen 2",
      connectivity: "2.4GHz wireless, Bluetooth, 3.5mm",
      battery: "Up to 44 hours",
    },
    stock: 55,
    sku: "STEELSERIES-ARCTIS-NOVA-PRO",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "ASUS ROG Swift PG32UQX",
    description: "32-inch 4K HDR gaming monitor with Mini LED",
    price: 2999.99,
    category: "monitors",
    brand: "ASUS",
    images: ["/images/asus-rog-swift-pg32uqx-1.jpg", "/images/asus-rog-swift-pg32uqx-2.jpg"],
    specifications: {
      size: "32-inch",
      resolution: "3840 x 2160 (4K UHD)",
      panel: "IPS with Mini LED backlight",
      refresh: "144Hz with G-SYNC Ultimate",
      hdr: "DisplayHDR 1400",
    },
    stock: 8,
    sku: "ASUS-ROG-PG32UQX",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Alienware AW3423DWF",
    description: "34-inch curved OLED gaming monitor with QD-OLED technology",
    price: 1099.99,
    category: "monitors",
    brand: "Dell",
    images: ["/images/alienware-aw3423dwf-1.jpg", "/images/alienware-aw3423dwf-2.jpg"],
    specifications: {
      size: "34-inch curved",
      resolution: "3440 x 1440 (UWQHD)",
      panel: "QD-OLED with infinite contrast",
      refresh: "165Hz with FreeSync Premium Pro",
      response: "0.1ms response time",
    },
    stock: 20,
    sku: "ALIENWARE-AW3423DWF",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Fujifilm X-T5",
    description: "Mirrorless camera with 40MP sensor and film simulation modes",
    price: 1699.99,
    category: "cameras",
    brand: "Fujifilm",
    images: ["/images/fujifilm-xt5-1.jpg", "/images/fujifilm-xt5-2.jpg"],
    specifications: {
      sensor: "40.2MP X-Trans CMOS 5 HR",
      processor: "X-Processor 5",
      video: "6.2K 30p, 4K 60p",
      stabilization: "7-stop in-body IS",
      features: "19 film simulation modes",
    },
    stock: 25,
    sku: "FUJIFILM-XT5-BODY",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "GoPro HERO12 Black",
    description: "Action camera with 5.3K video and enhanced stabilization",
    price: 399.99,
    category: "cameras",
    brand: "GoPro",
    images: ["/images/gopro-hero12-1.jpg", "/images/gopro-hero12-2.jpg"],
    specifications: {
      video: "5.3K60, 4K120, 2.7K240",
      photo: "27MP photos",
      stabilization: "HyperSmooth 6.0",
      features: "HDR video, TimeWarp 3.0",
      waterproof: "33ft (10m) without housing",
    },
    stock: 80,
    sku: "GOPRO-HERO12-BLACK",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Insta360 X4",
    description: "360-degree action camera with 8K video recording",
    price: 499.99,
    category: "cameras",
    brand: "Insta360",
    images: ["/images/insta360-x4-1.jpg", "/images/insta360-x4-2.jpg"],
    specifications: {
      video: "8K30fps 360°, 4K60fps single-lens",
      photo: "72MP 360° photos",
      stabilization: "FlowState stabilization",
      features: "AI editing, invisible selfie stick",
      waterproof: "33ft (10m) with case",
    },
    stock: 35,
    sku: "INSTA360-X4",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Fitbit Charge 6",
    description: "Advanced fitness tracker with built-in GPS and Google apps",
    price: 159.99,
    category: "wearables",
    brand: "Fitbit",
    images: ["/images/fitbit-charge-6-1.jpg", "/images/fitbit-charge-6-2.jpg"],
    specifications: {
      display: "1.04-inch color AMOLED",
      battery: "Up to 7 days",
      features: "Built-in GPS, Google Pay, YouTube Music",
      sensors: "Heart rate, SpO2, stress management",
      waterproof: "50m water resistant",
    },
    stock: 120,
    sku: "FITBIT-CHARGE-6-BLACK",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Garmin Fenix 7X Sapphire",
    description: "Premium multisport GPS watch with solar charging",
    price: 899.99,
    category: "wearables",
    brand: "Garmin",
    images: ["/images/garmin-fenix-7x-1.jpg", "/images/garmin-fenix-7x-2.jpg"],
    specifications: {
      display: "1.4-inch sunlight-readable",
      battery: "Up to 37 days with solar",
      features: "Multi-GNSS, TopoActive maps",
      sensors: "Pulse Ox, respiration, body battery",
      build: "Sapphire crystal lens, titanium bezel",
    },
    stock: 30,
    sku: "GARMIN-FENIX-7X-SAPPHIRE",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Philips Hue Play HDMI Sync Box",
    description: "Smart lighting sync box for immersive entertainment",
    price: 229.99,
    category: "smart-home",
    brand: "Philips",
    images: ["/images/philips-hue-sync-box-1.jpg", "/images/philips-hue-sync-box-2.jpg"],
    specifications: {
      inputs: "4x HDMI 2.0 inputs, 1x HDMI output",
      resolution: "Up to 4K HDR at 60Hz",
      features: "Real-time color sync with Hue lights",
      compatibility: "Works with all HDMI devices",
      control: "Hue Sync mobile app",
    },
    stock: 45,
    sku: "PHILIPS-HUE-SYNC-BOX",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ring Video Doorbell Pro 2",
    description: "Smart doorbell with 1536p HD video and 3D motion detection",
    price: 249.99,
    category: "smart-home",
    brand: "Ring",
    images: ["/images/ring-doorbell-pro-2-1.jpg", "/images/ring-doorbell-pro-2-2.jpg"],
    specifications: {
      video: "1536p HD with HDR",
      field: "150° diagonal field of view",
      features: "3D motion detection, Bird's Eye View",
      power: "Hardwired (existing doorbell wiring)",
      storage: "Cloud recording with Ring Protect plan",
    },
    stock: 70,
    sku: "RING-DOORBELL-PRO-2",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Nest Thermostat",
    description: "Smart thermostat with energy-saving features and remote control",
    price: 129.99,
    category: "smart-home",
    brand: "Google",
    images: ["/images/nest-thermostat-1.jpg", "/images/nest-thermostat-2.jpg"],
    specifications: {
      display: "Mirrored display with Farsight",
      compatibility: "Works with 95% of systems",
      features: "Auto-schedule, energy history",
      control: "Google Home app, voice control",
      sensors: "Temperature, humidity, proximity",
    },
    stock: 85,
    sku: "NEST-THERMOSTAT-SNOW",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Sonos Era 300",
    description: "Premium smart speaker with spatial audio and Dolby Atmos",
    price: 449.99,
    category: "audio",
    brand: "Sonos",
    images: ["/images/sonos-era-300-1.jpg", "/images/sonos-era-300-2.jpg"],
    specifications: {
      drivers: "6 drivers including upward-firing",
      features: "Spatial audio, Dolby Atmos, Trueplay",
      connectivity: "Wi-Fi, Bluetooth, USB-C line-in",
      control: "Sonos app, voice assistants",
      design: "360-degree sound with room-filling audio",
    },
    stock: 40,
    sku: "SONOS-ERA-300-BLACK",
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Audio-Technica AT2020USB+",
    description: "Professional USB condenser microphone for streaming and recording",
    price: 169.99,
    category: "audio",
    brand: "Audio-Technica",
    images: ["/images/audio-technica-at2020usb-1.jpg", "/images/audio-technica-at2020usb-2.jpg"],
    specifications: {
      type: "Side-address condenser microphone",
      pattern: "Cardioid polar pattern",
      frequency: "20Hz - 20kHz",
      connectivity: "USB-C and XLR outputs",
      features: "Zero-latency headphone monitoring",
    },
    stock: 60,
    sku: "AUDIO-TECHNICA-AT2020USB-PLUS",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Elgato Stream Deck MK.2",
    description: "Content creation controller with 15 customizable LCD keys",
    price: 149.99,
    category: "accessories",
    brand: "Elgato",
    images: ["/images/elgato-stream-deck-mk2-1.jpg", "/images/elgato-stream-deck-mk2-2.jpg"],
    specifications: {
      keys: "15 customizable LCD keys",
      resolution: "72x72 pixels per key",
      connectivity: "USB-C",
      compatibility: "Windows 10+, macOS 10.14+",
      features: "Multi-actions, smart profiles, plugins",
    },
    stock: 55,
    sku: "ELGATO-STREAM-DECK-MK2",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Blue Yeti X",
    description: "Professional USB microphone with real-time LED meter",
    price: 169.99,
    category: "audio",
    brand: "Blue",
    images: ["/images/blue-yeti-x-1.jpg", "/images/blue-yeti-x-2.jpg"],
    specifications: {
      capsules: "Four-capsule condenser array",
      patterns: "Cardioid, bidirectional, omnidirectional, stereo",
      features: "Real-time LED meter, smart knob",
      connectivity: "USB, headphone monitoring",
      compatibility: "PC, Mac, PS4, PS5",
    },
    stock: 45,
    sku: "BLUE-YETI-X-BLACK",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Rode PodMic USB",
    description: "Dynamic microphone designed specifically for podcasting",
    price: 199.99,
    category: "audio",
    brand: "Rode",
    images: ["/images/rode-podmic-usb-1.jpg", "/images/rode-podmic-usb-2.jpg"],
    specifications: {
      type: "Dynamic microphone",
      pattern: "Cardioid polar pattern",
      connectivity: "USB-C and XLR outputs",
      features: "Zero-latency headphone monitoring",
      design: "Internal pop shield, swing mount included",
    },
    stock: 35,
    sku: "RODE-PODMIC-USB",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Western Digital Black SN850X",
    description: "High-performance NVMe SSD for gaming and content creation",
    price: 199.99,
    category: "storage",
    brand: "Western Digital",
    images: ["/images/wd-black-sn850x-1.jpg", "/images/wd-black-sn850x-2.jpg"],
    specifications: {
      capacity: "2TB",
      interface: "PCIe Gen4 x4",
      speed: "Up to 7,300 MB/s read",
      features: "Game Mode 2.0, RGB lighting",
      compatibility: "PS5 compatible with heatsink",
    },
    stock: 50,
    sku: "WD-BLACK-SN850X-2TB",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Seagate FireCuda 530",
    description: "PCIe Gen4 NVMe SSD with heatsink for extreme performance",
    price: 249.99,
    category: "storage",
    brand: "Seagate",
    images: ["/images/seagate-firecuda-530-1.jpg", "/images/seagate-firecuda-530-2.jpg"],
    specifications: {
      capacity: "2TB",
      interface: "PCIe Gen4 x4 NVMe",
      speed: "Up to 7,300 MB/s read",
      features: "Built-in heatsink, 5-year warranty",
      endurance: "2,550 TBW",
    },
    stock: 40,
    sku: "SEAGATE-FIRECUDA-530-2TB",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Crucial P5 Plus",
    description: "PCIe 4.0 NVMe SSD with advanced security features",
    price: 179.99,
    category: "storage",
    brand: "Crucial",
    images: ["/images/crucial-p5-plus-1.jpg", "/images/crucial-p5-plus-2.jpg"],
    specifications: {
      capacity: "2TB",
      interface: "PCIe 4.0 NVMe",
      speed: "Up to 6,600 MB/s read",
      features: "Hardware-based security, power loss immunity",
      warranty: "5-year limited warranty",
    },
    stock: 65,
    sku: "CRUCIAL-P5-PLUS-2TB",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "NETGEAR Nighthawk AX12",
    description: "12-stream WiFi 6 router with 10.8 Gbps speeds",
    price: 449.99,
    category: "networking",
    brand: "NETGEAR",
    images: ["/images/netgear-nighthawk-ax12-1.jpg", "/images/netgear-nighthawk-ax12-2.jpg"],
    specifications: {
      standard: "WiFi 6 (802.11ax)",
      speed: "Up to 10.8 Gbps",
      coverage: "Up to 3,500 sq ft",
      ports: "1x 5G Multi-Gig, 4x Gigabit Ethernet",
      features: "Dynamic QoS, VPN support",
    },
    stock: 30,
    sku: "NETGEAR-NIGHTHAWK-AX12",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "TP-Link Archer AXE75",
    description: "Tri-band WiFi 6E router with 6 GHz band support",
    price: 299.99,
    category: "networking",
    brand: "TP-Link",
    images: ["/images/tp-link-archer-axe75-1.jpg", "/images/tp-link-archer-axe75-2.jpg"],
    specifications: {
      standard: "WiFi 6E (802.11ax)",
      speed: "Up to 5.4 Gbps",
      bands: "2.4 GHz, 5 GHz, 6 GHz",
      ports: "1x 2.5G WAN/LAN, 4x Gigabit LAN",
      features: "OneMesh support, HomeShield security",
    },
    stock: 45,
    sku: "TP-LINK-ARCHER-AXE75",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ubiquiti Dream Machine",
    description: "All-in-one security gateway and WiFi 6 access point",
    price: 379.99,
    category: "networking",
    brand: "Ubiquiti",
    images: ["/images/ubiquiti-dream-machine-1.jpg", "/images/ubiquiti-dream-machine-2.jpg"],
    specifications: {
      features: "Security gateway, switch, WiFi 6 AP",
      throughput: "Up to 3.5 Gbps",
      ports: "1x WAN, 4x LAN Gigabit",
      management: "UniFi Network application",
      security: "IDS/IPS, DPI, firewall",
    },
    stock: 25,
    sku: "UBIQUITI-DREAM-MACHINE",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Anker PowerCore III Elite 25600",
    description: "High-capacity power bank with 87W USB-C PD charging",
    price: 149.99,
    category: "accessories",
    brand: "Anker",
    images: ["/images/anker-powercore-iii-elite-1.jpg", "/images/anker-powercore-iii-elite-2.jpg"],
    specifications: {
      capacity: "25600mAh",
      output: "87W USB-C PD, 18W USB-A",
      features: "Trickle-charging mode, LED display",
      compatibility: "MacBook, iPad, iPhone, Samsung",
      recharge: "3.5 hours with 65W charger",
    },
    stock: 70,
    sku: "ANKER-POWERCORE-III-ELITE-25600",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "RAVPower 90W GaN Charger",
    description: "Compact 4-port GaN charger with intelligent power distribution",
    price: 79.99,
    category: "accessories",
    brand: "RAVPower",
    images: ["/images/ravpower-90w-gan-1.jpg", "/images/ravpower-90w-gan-2.jpg"],
    specifications: {
      power: "90W total output",
      ports: "2x USB-C PD, 2x USB-A",
      technology: "GaN (Gallium Nitride)",
      features: "Intelligent power distribution",
      size: "40% smaller than traditional chargers",
    },
    stock: 85,
    sku: "RAVPOWER-90W-GAN-CHARGER",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "CalDigit TS4 Thunderbolt 4 Dock",
    description: "18-port Thunderbolt 4 dock with 98W charging",
    price: 399.99,
    category: "accessories",
    brand: "CalDigit",
    images: ["/images/caldigit-ts4-1.jpg", "/images/caldigit-ts4-2.jpg"],
    specifications: {
      ports: "18 total ports including 3x Thunderbolt 4",
      charging: "98W laptop charging",
      display: "Support for up to 8K or dual 4K displays",
      connectivity: "USB-A, USB-C, SD, microSD, Ethernet",
      compatibility: "Mac and PC compatible",
    },
    stock: 20,
    sku: "CALDIGIT-TS4-DOCK",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Twelve South BookArc Flex",
    description: "Adjustable vertical stand for MacBook and laptops",
    price: 49.99,
    category: "accessories",
    brand: "Twelve South",
    images: ["/images/twelve-south-bookarc-flex-1.jpg", "/images/twelve-south-bookarc-flex-2.jpg"],
    specifications: {
      compatibility: "MacBook Air, MacBook Pro, PC laptops",
      material: "Chrome-plated steel with silicone inserts",
      adjustment: 'Arc width adjusts from 0.68" to 1.02"',
      design: "Space-saving vertical orientation",
      protection: "Silicone cradle protects laptop finish",
    },
    stock: 95,
    sku: "TWELVE-SOUTH-BOOKARC-FLEX",
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

async function seedProducts() {
  let client

  try {
    client = await MongoClient.connect(MONGODB_URI)
    const db = client.db()

    console.log("Connected to MongoDB")

    await db.collection("products").deleteMany({})
    console.log("Cleared existing products")

    const result = await db.collection("products").insertMany(Products)
    console.log(`Inserted ${result.insertedCount} products`)

    await db.collection("products").createIndex({ name: "text", description: "text", brand: "text" })
    await db.collection("products").createIndex({ category: 1 })
    await db.collection("products").createIndex({ brand: 1 })
    await db.collection("products").createIndex({ price: 1 })
    await db.collection("products").createIndex({ sku: 1 }, { unique: true })
    await db.collection("products").createIndex({ featured: 1 })
    await db.collection("products").createIndex({ createdAt: -1 })

    console.log("Created database indexes")
    console.log("Database seeding completed successfully!")
  } catch (error) {
    console.error("Error seeding database:", error)
  } finally {
    if (client) {
      await client.close()
    }
  }
}

seedProducts()
